Less 04
prapeller/geekbrains_javascript pull request #4
Opened 2021-08-21 15:40 UTC by prapeller

2021-08-30 22:37 UTC, Om1X requested changes

2021-08-30 22:37 UTC, Om1X commented on less_04/hw/script2-3.js
> +        if (this.items.filter(e => e.name === item.name).length > 0) {
тут логичней использовать метод find вместо fiter

2021-08-30 22:37 UTC, Om1X commented on less_04/hw/script2-3.js
> +        this.items = this.items.filter(e => e.name !== item.name)
тут разумней использовать связку find / splice

2021-09-01 13:15 UTC, prapeller commented on less_04/hw/script2-3.js
> +        this.items = this.items.filter(e => e.name !== item.name)
например так?
    removeItem(item) {
        let e = this.items.find(e => e.name === item.name)
        e ? this.items.splice(this.items.indexOf(e), 1) : null
    },
мне кажется filter попроще, нет?

2021-09-01 13:17 UTC, prapeller commented on less_04/hw/script2-3.js
> +        if (this.items.filter(e => e.name === item.name).length > 0) {
заменил на
addItem(item) {
let e = this.items.find(e => e.name === item.name)
e ? e['qty'] += 1 : this.items.push(item)
},

спасибо

2021-09-01 13:18 UTC, merged